# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2QxMlUctdIbka_vYh5AZPOhjT_3enh-
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = "/content/drive/MyDrive/251MI71_Group05_DA/data_preprocessing.csv"
df = pd.read_csv(file_path)

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
from datetime import datetime, timedelta

# Load your data from the CSV file
file_path = "/content/drive/MyDrive/251MI71_Group05_DA/data_preprocessing.csv"
df = pd.read_csv(file_path)

# Convert date column to datetime objects
df['publishedDate'] = pd.to_datetime(df['publishedDate'])

# Calculate sentiment counts per day
sentiment_data = df.groupby('publishedDate')['sentiment_label'].value_counts().unstack(fill_value=0).reset_index()
sentiment_data = sentiment_data.rename(columns={'Positive': 'positive', 'Negative': 'negative', 'Neutral': 'neutral', 'publishedDate': 'date'})

# Calculate monthly aggregates
sentiment_data['month'] = sentiment_data['date'].dt.month
monthly_sentiment = sentiment_data.groupby('month')[['positive', 'negative', 'neutral']].sum().reset_index()

# Create the main dashboard
fig = make_subplots(
    rows=3, cols=3,
    specs=[
        [{"type": "indicator", "rowspan": 2}, {"type": "scatter", "colspan": 2, "rowspan": 2}, None],
        [None, None, None],
        [{"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"}]
    ],
    subplot_titles=('', 'Sentiment Distribution Over Time', '', '', '', ''),
    vertical_spacing=0.12,
    horizontal_spacing=0.1
)

# Color scheme matching the reference dashboard
colors = {
    'bg': '#0a1929',
    'primary': '#1e88e5',
    'secondary': '#26c6da',
    'success': '#66bb6a',
    'warning': '#ffa726',
    'danger': '#ef5350',
    'text': '#ffffff'
}

# 1. Main KPI Indicator - Total Sentiments
total_sentiments = sentiment_data[['positive', 'negative', 'neutral']].sum().sum()
positive_pct = (sentiment_data['positive'].sum() / total_sentiments * 100)

fig.add_trace(go.Indicator(
    mode="number+delta",
    value=total_sentiments,
    title={'text': "Total Sentiments<br><span style='font-size:0.8em;color:gray'>Overall</span>"},
    # Remove delta since we don't have a reference point in this dataset
    number={'valueformat': ',', 'font': {'size': 50}},
    domain={'x': [0, 1], 'y': [0, 1]}
), row=1, col=1)

# 2. Area Chart - Sentiment Trends
fig.add_trace(go.Scatter(
    x=sentiment_data['date'],
    y=sentiment_data['positive'],
    name='Positive',
    mode='lines',
    line=dict(width=0.5, color=colors['success']),
    stackgroup='one',
    fillcolor=f"rgba(102, 187, 106, 0.6)"
), row=1, col=2)

fig.add_trace(go.Scatter(
    x=sentiment_data['date'],
    y=sentiment_data['neutral'],
    name='Neutral',
    mode='lines',
    line=dict(width=0.5, color=colors['secondary']),
    stackgroup='one',
    fillcolor=f"rgba(38, 198, 218, 0.6)"
), row=1, col=2)

fig.add_trace(go.Scatter(
    x=sentiment_data['date'],
    y=sentiment_data['negative'],
    name='Negative',
    mode='lines',
    line=dict(width=0.5, color=colors['danger']),
    stackgroup='one',
    fillcolor=f"rgba(239, 83, 80, 0.6)"
), row=1, col=2)

# 3. Bottom KPIs - Sentiment Percentages
positive_total = sentiment_data['positive'].sum()
negative_total = sentiment_data['negative'].sum()
neutral_total = sentiment_data['neutral'].sum()

fig.add_trace(go.Indicator(
    mode="number+gauge",
    value=positive_pct,
    title={'text': "Positive<br>Sentiment"},
    number={'suffix': "%", 'valueformat': '.1f', 'font': {'size': 40, 'color': colors['success']}},
    gauge={
        'shape': "bullet",
        'axis': {'range': [None, 100]},
        'bar': {'color': colors['success']},
        'bgcolor': "rgba(255,255,255,0.1)",
    },
    domain={'x': [0, 1], 'y': [0, 1]}
), row=3, col=1)

negative_pct = (negative_total / total_sentiments * 100)
fig.add_trace(go.Indicator(
    mode="number+gauge",
    value=negative_pct,
    title={'text': "Negative<br>Sentiment"},
    number={'suffix': "%", 'valueformat': '.1f', 'font': {'size': 40, 'color': colors['danger']}},
    gauge={
        'shape': "bullet",
        'axis': {'range': [None, 100]},
        'bar': {'color': colors['danger']},
        'bgcolor': "rgba(255,255,255,0.1)",
    },
    domain={'x': [0, 1], 'y': [0, 1]}
), row=3, col=2)

neutral_pct = (neutral_total / total_sentiments * 100)
fig.add_trace(go.Indicator(
    mode="number+gauge",
    value=neutral_pct,
    title={'text': "Neutral<br>Sentiment"},
    number={'suffix': "%", 'valueformat': '.1f', 'font': {'size': 40, 'color': colors['secondary']}},
    gauge={
        'shape': "bullet",
        'axis': {'range': [None, 100]},
        'bar': {'color': colors['secondary']},
        'bgcolor': "rgba(255,255,255,0.1)",
    },
    domain={'x': [0, 1], 'y': [0, 1]}
), row=3, col=3)

# Update layout
fig.update_layout(
    title={
        'text': "Sentiment Analysis & Seasonal Trends Dashboard",
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 28, 'color': colors['text'], 'family': 'Arial Black'}
    },
    showlegend=True,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=0.45,
        xanchor="right",
        x=0.98,
        bgcolor="rgba(0,0,0,0.5)",
        font=dict(color=colors['text'])
    ),
    plot_bgcolor=colors['bg'],
    paper_bgcolor=colors['bg'],
    font=dict(color=colors['text'], family='Arial'),
    height=900,
    margin=dict(t=100, l=50, r=50, b=50)
)

# Update axes
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='rgba(255,255,255,0.1)',
                 showline=True, linewidth=2, linecolor='rgba(255,255,255,0.2)')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='rgba(255,255,255,0.1)',
                 showline=True, linewidth=2, linecolor='rgba(255,255,255,0.2)')

fig.show()

# Create a second dashboard for seasonal analysis
fig2 = make_subplots(
    rows=2, cols=2,
    specs=[
        [{"type": "bar"}, {"type": "domain"}],
        [{"type": "scatter", "colspan": 2}, None]
    ],
    subplot_titles=('Monthly Sentiment Distribution', 'Sentiment Composition',
                    'Seasonal Trends Analysis'),
    vertical_spacing=0.15,
    horizontal_spacing=0.12
)

# Monthly bar chart
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
fig2.add_trace(go.Bar(
    x=months,
    y=monthly_sentiment['positive'],
    name='Positive',
    marker_color=colors['success']
), row=1, col=1)

fig2.add_trace(go.Bar(
    x=months,
    y=monthly_sentiment['neutral'],
    name='Neutral',
    marker_color=colors['secondary']
), row=1, col=1)

fig2.add_trace(go.Bar(
    x=months,
    y=monthly_sentiment['negative'],
    name='Negative',
    marker_color=colors['danger']
), row=1, col=1)

# Pie chart
fig2.add_trace(go.Pie(
    labels=['Positive', 'Neutral', 'Negative'],
    values=[positive_total, neutral_total, negative_total],
    marker=dict(colors=[colors['success'], colors['secondary'], colors['danger']]),
    hole=0.4,
    textinfo='label+percent',
    textfont=dict(size=14, color='white')
), row=1, col=2)

# Seasonal trend line
# Calculate rolling averages directly on sentiment_data which is grouped by date
sentiment_data['rolling_positive'] = sentiment_data['positive'].rolling(window=7).mean()
sentiment_data['rolling_negative'] = sentiment_data['negative'].rolling(window=7).mean()
sentiment_data['rolling_neutral'] = sentiment_data['neutral'].rolling(window=7).mean()

fig2.add_trace(go.Scatter(
    x=sentiment_data['date'],
    y=sentiment_data['rolling_positive'],
    name='Positive (7-day avg)',
    line=dict(color=colors['success'], width=3)
), row=2, col=1)

fig2.add_trace(go.Scatter(
    x=sentiment_data['date'],
    y=sentiment_data['rolling_neutral'],
    name='Neutral (7-day avg)',
    line=dict(color=colors['secondary'], width=3)
), row=2, col=1)

fig2.add_trace(go.Scatter(
    x=sentiment_data['date'],
    y=sentiment_data['rolling_negative'],
    name='Negative (7-day avg)',
    line=dict(color=colors['danger'], width=3)
), row=2, col=1)

fig2.update_layout(
    title={
        'text': "Seasonal Sentiment Analysis Dashboard",
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 28, 'color': colors['text'], 'family': 'Arial Black'}
    },
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="middle",
        y=0.5,
        xanchor="right",
        x=1.15,
        bgcolor="rgba(0,0,0,0.5)",
        font=dict(color=colors['text'])
    ),
    plot_bgcolor=colors['bg'],
    paper_bgcolor=colors['bg'],
    font=dict(color=colors['text'], family='Arial'),
    height=900,
    barmode='group'
)

fig2.update_xaxes(showgrid=True, gridwidth=1, gridcolor='rgba(255,255,255,0.1)')
fig2.update_yaxes(showgrid=True, gridwidth=1, gridcolor='rgba(255,255,255,0.1)')

fig2.show()

# Print summary statistics
print("\n" + "="*60)
print("SENTIMENT ANALYSIS SUMMARY")
print("="*60)
print(f"Total Sentiments Analyzed: {total_sentiments:,}")
print(f"Positive Sentiment: {positive_pct:.1f}% ({positive_total:,})")
print(f"Neutral Sentiment: {neutral_pct:.1f}% ({neutral_total:,})")
print(f"Negative Sentiment: {negative_pct:.1f}% ({negative_total:,})")
print("="*60)
# Find the month with the most positive and negative sentiment
# Need to use monthly_sentiment for this
most_positive_month_index = monthly_sentiment['positive'].idxmax()
most_negative_month_index = monthly_sentiment['negative'].idxmax()

# Map month index back to month name
month_names = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
most_positive_month = month_names[most_positive_month_index - 1] # Adjust for 0-based indexing
most_negative_month = month_names[most_negative_month_index - 1] # Adjust for 0-based indexing

print(f"\nMost Positive Month: {most_positive_month}")
print(f"Most Negative Month: {most_negative_month}")
print("="*60)