# -*- coding: utf-8 -*-
"""data_visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3QG4cYcOOB4pxaGb__rZ7pU-wlZVMkY
"""

from google.colab import drive
drive.mount('/content/drive')

#Lấy file data_preprocessing.csv từ Google Drive: 251MI71_Group05_DA
import pandas as pd

file_path = "/content/drive/MyDrive/251MI71_Group05_DA/data_preprocessing.csv"
df = pd.read_csv(file_path)
#Hoặc dùng "from google.colab import files uploaded = files.upload()" để upload dựa vào file có sẵn trên máy

import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Load dataset
file_path = "/content/drive/MyDrive/251MI71_Group05_DA/data_preprocessing.csv"
df = pd.read_csv(file_path)

# Chuyển publishedDate về dạng datetime
df['publishedDate'] = pd.to_datetime(df['publishedDate'], errors='coerce')

#Sentiment Category Summary Table
# Ensure sentiment_label column exists and is standardized
df['sentiment_label'] = df['sentiment_label'].astype(str).str.strip().str.capitalize()

# Exact counts and percentages
counts = df['sentiment_label'].value_counts()
percentages = df['sentiment_label'].value_counts(normalize=True) * 100

summary = pd.DataFrame({
    'Number of Reviews': counts,
    'Percentage (%)': percentages.round(2)
}).reindex(['Positive','Neutral','Negative']).fillna(0).astype({'Number of Reviews':'int','Percentage (%)':'float'})

print("Dataset size:", len(df))
summary

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
file_path = "/content/drive/MyDrive/251MI71_Group05_DA/data_preprocessing.csv"
df = pd.read_csv(file_path)

sentiment_counts = df['sentiment_label'].value_counts()

plt.figure(figsize=(6,4))
sentiment_counts.plot(kind='bar', color=['green', 'red', 'gray'])
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.show()

plt.figure(figsize=(6,6))
sentiment_counts.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['green', 'red', 'gray'])
plt.title("Sentiment Composition")
plt.ylabel("")
plt.show()

# Average sentiment_score by month
trend = df.groupby(df['publishedDate'].dt.to_period("M"))['sentiment_score'].mean()

plt.figure(figsize=(8,4))
trend.plot(kind='line', marker='o', title="Average Sentiment Score Over Time")
plt.xlabel("Month")
plt.ylabel("Average Sentiment Score")
plt.show()

# WordCloud for Positive, Negative and Neutral Reviews
for sentiment_type in df['sentiment_label'].unique():
    text = " ".join(df[df['sentiment_label'] == sentiment_type]['processed_text'].astype(str))
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
    plt.figure(figsize=(8,4))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis("off")
    plt.title(f"Word Cloud – {sentiment_type} Reviews")
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import calendar

df['publishedDate'] = pd.to_datetime(df['publishedDate'], errors='coerce')

# Tạo cột Month (1–12)
df['Month'] = df['publishedDate'].dt.month

# Tính trung bình sentiment cho từng tháng (gộp tất cả các năm)
month_avg = df.groupby('Month')['sentiment_score'].mean().reset_index()

# Thêm tên tháng
month_avg['MonthName'] = month_avg['Month'].apply(lambda x: calendar.month_name[x])

# Sắp xếp thứ tự tháng
month_avg = month_avg.sort_values('Month')
month_avg

plt.figure(figsize=(10,5))
plt.plot(month_avg['MonthName'], month_avg['sentiment_score'],
         marker='o', color='royalblue', linewidth=2)

# Add text labels for each point
for index, row in month_avg.iterrows():
    plt.text(row['MonthName'], row['sentiment_score'], f"{row['sentiment_score']:.2f}",
             fontsize=9, ha='center', va='bottom')


plt.title("Average Monthly Sentiment Score (2018–2025)", fontsize=15, fontweight='bold')
plt.xlabel("Month")
plt.ylabel("Average Sentiment Score")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()