# -*- coding: utf-8 -*-
"""data_with_vader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHp_vgJsLFb6SnavO41IRhi-mzBLoYvA
"""

!pip install vaderSentiment

from google.colab import drive
drive.mount('/content/drive')

#Lấy file data_preprocessing.csv từ Google Drive: 251MI71_Group05_DA
import pandas as pd

file_path = "/content/drive/MyDrive/251MI71_Group05_DA/data_preprocessing.csv"
df = pd.read_csv(file_path)
#Hoặc dùng "from google.colab import files uploaded = files.upload()" để upload dựa vào file có sẵn trên máy

import pandas as pd

file_path = "/content/data_preprocessing.csv"
df = pd.read_csv(file_path)
# Xem trước vài dòng dữ liệu
display(df.head())

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

#Tính điểm và nhãn cảm xúc bằng VADER
def get_vader_sentiment(text):
    score = analyzer.polarity_scores(str(text))['compound']
    if score >= 0.05:
        label = 'Positive'
    elif score <= -0.05:
        label = 'Negative'
    else:
        label = 'Neutral'
    return pd.Series([score, label])

df[['vader_score', 'vader_label']] = df['processed_text'].apply(get_vader_sentiment)
display(df.head())

#Vẽ thử phân bố
import seaborn as sns
sns.boxplot(x='vader_label', y='final_rating', data=df)

#Phân tích xu hướng cảm xúc theo mùa
df.groupby('season')['vader_score'].mean().sort_values(ascending=False)

#Thống kê tỷ lệ sentiment
sentiment_counts = df['vader_label'].value_counts(normalize=True) * 100
sentiment_counts

#Phân tích Seasonal Sentiment Trend Tính điểm trung bình cảm xúc theo mùa:
seasonal_sentiment = df.groupby('season')['vader_score'].agg(['mean', 'count']).sort_values('mean', ascending=False)
seasonal_sentiment

#Vẽ biểu đồ
import matplotlib.pyplot as plt

seasonal_sentiment['mean'].plot(kind='bar', title='Average Sentiment Score by Season', ylabel='Mean VADER Score')
plt.show()

#Kiểm chứng mô hình (Validation)
df['final_rating'] = pd.to_numeric(df['final_rating'], errors='coerce')
corr = df['vader_score'].corr(df['final_rating'])
print("Correlation between VADER score and rating:", corr)

df.to_csv("/content/data_with_vader.csv", index=False)