# -*- coding: utf-8 -*-
"""Logistic Regression, XGBoost (input: TF-IDF).

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4PRVnvaK1nlbx0J7xrEJwsOm2p4yZ-e
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# === cấu hình tên cột ===
CSV_PATH   = "data preprocessing.csv"  # đúng tên file vừa upload
TEXT_COL   = "cleaned_text"
LABEL_COL  = "sentiment_label"

# === đọc csv ===
df = pd.read_csv(CSV_PATH)
print("Các cột có trong file:", list(df.columns))

# lọc dữ liệu hợp lệ
df = df.dropna(subset=[TEXT_COL, LABEL_COL])
df = df[df[TEXT_COL].astype(str).str.strip().astype(bool)].copy()

# chuẩn hoá nhãn về 3 lớp
df[LABEL_COL] = df[LABEL_COL].astype(str).str.lower().str.strip()
mapping = {
    "neg":"negative","negatives":"negative","negative":"negative",
    "neu":"neutral","neutral":"neutral",
    "pos":"positive","positives":"positive","positive":"positive"
}
df[LABEL_COL] = df[LABEL_COL].map(lambda x: mapping.get(x, x))
df = df[df[LABEL_COL].isin(["negative","neutral","positive"])].copy()

print("\nPhân bố nhãn:")
print(df[LABEL_COL].value_counts())

# tạo X_text, y
X_text = df[TEXT_COL].astype(str)
y_raw  = df[LABEL_COL].astype(str)

# encode nhãn
le = LabelEncoder()
y = le.fit_transform(y_raw)            # y là số 0..2
label_names = list(le.classes_)        # ['negative','neutral','positive']
print("\nThứ tự nhãn:", label_names)

!pip install -q scikit-learn xgboost pandas numpy matplotlib seaborn

from google.colab import files
uploaded = files.upload()  # chọn file: data preprocessing.csv

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

TEST_SIZE   = 0.2
RANDOM_SEED = 42

# chia dữ liệu train/test
X_train, X_test, y_train, y_test = train_test_split(
    X_text, y, test_size=TEST_SIZE, random_state=RANDOM_SEED, stratify=y
)

# chuyển văn bản thành vector TF-IDF
tfidf = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1,2),   # unigram + bigram
    min_df=5,            # bỏ từ xuất hiện quá ít
    max_df=0.9           # bỏ từ quá phổ biến
)

Xtr = tfidf.fit_transform(X_train)
Xte = tfidf.transform(X_test)

print("Kích thước TF-IDF train:", Xtr.shape)
print("Kích thước TF-IDF test:", Xte.shape)

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns, matplotlib.pyplot as plt

# --- huấn luyện Logistic Regression ---
lr = LogisticRegression(
    max_iter=1500,
    solver='liblinear',       # ổn định cho dữ liệu thưa
    multi_class='ovr',
    class_weight='balanced',  # cân bằng giữa các lớp
    random_state=42
)
lr.fit(Xtr, y_train)

# --- dự đoán ---
y_pred_lr = lr.predict(Xte)

# --- báo cáo ---
print("\n[Logistic Regression] Classification Report")
print(classification_report(y_test, y_pred_lr, target_names=label_names))

# --- Confusion Matrix ---
cm_lr = confusion_matrix(y_test, y_pred_lr, labels=range(len(label_names)))
plt.figure(figsize=(5.2,4.6))
sns.heatmap(cm_lr, annot=True, fmt="d", cmap="Blues",
            xticklabels=label_names, yticklabels=label_names)
plt.title("Confusion Matrix — Logistic Regression")
plt.xlabel("Predicted"); plt.ylabel("True")
plt.tight_layout(); plt.show()

# --- Top từ khoá ảnh hưởng đến từng lớp ---
try:
    feats = np.array(tfidf.get_feature_names_out())
    for ci, cname in enumerate(label_names):
        coefs = lr.coef_[ci]
        top_idx = np.argsort(coefs)[-15:]
        print(f"\n[LogReg] Top features → '{cname}':")
        print(", ".join(feats[top_idx]))
except Exception as e:
    print("Skip top features:", e)

import os
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns, matplotlib.pyplot as plt

# nếu bạn bật GPU: Runtime > Change runtime type > GPU
# thì dùng tree_method='gpu_hist' (nhanh hơn)
tree_method = "gpu_hist" if os.environ.get("COLAB_GPU") else "hist"
print("Tree method:", tree_method)

xgb = XGBClassifier(
    n_estimators=200,     # giảm để chạy nhanh (có thể tăng 300-500 nếu dư thời gian)
    max_depth=6,
    learning_rate=0.2,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=1.0,
    objective="multi:softprob",
    eval_metric="mlogloss",
    random_state=RANDOM_SEED,
    tree_method=tree_method
)

xgb.fit(Xtr, y_train)
y_pred_xgb = xgb.predict(Xte)

print("\n[XGBoost] Classification Report")
print(classification_report(y_test, y_pred_xgb, target_names=label_names))

cm_xgb = confusion_matrix(y_test, y_pred_xgb, labels=range(len(label_names)))
plt.figure(figsize=(5.2,4.6))
sns.heatmap(cm_xgb, annot=True, fmt="d", cmap="Greens",
            xticklabels=label_names, yticklabels=label_names)
plt.title("Confusion Matrix — XGBoost")
plt.xlabel("Predicted"); plt.ylabel("True")
plt.tight_layout(); plt.show()

"""*italicized text*"""